### ISSUE TITLE
cannot load such file --avatarly

### ISSUE THREAD

**Issue by benkoshy** [lucek/avatarly#20]
Hi there

Thank you for your gem.

Was hoping for a pointer. 

Steps to reproduce:

1. add avatarly to gem file.
2. run `bundle install`
3. spin up a `rails c` and try: `require "avatarly"` -- and I'm getting a: 

> LoadError (cannot load such file -- avatarly)

any pointers in the right direction would be much appreciated.

cheers

Ben

**Comment by WaKeMaTTa** [comment]
Close the terminal, and try again `bin/rails c` + `require "avatarly"`

**Comment by benkoshy** [comment]
@WaKeMaTTa hey thanks for your comment.

What i'm really trying to do is to create an avatar in a background job.

```ruby
require "avatarly" # cannot load such file --avatarly

class PlainOldRubyObject
   def generate_avatar
       Avatarly.generate_avatar # etc.
   end

end
```

Any pointers on the above would be much appreciated, chrs

**Comment by ArturT** [comment]
Have you added `gem "avatarly"` in Gemfile or only in a specific group-like development (this could narrow down if the gem is available for a certain environment)?

Regarding worker. Please try to stop it & start (if you use sidekiq). If you use spring gem you may want to run `spring stop` to stop the cached state of gems from the memory and then try run worker (sidekiq) again.

**Comment by benkoshy** [comment]
@ArturT thank you, the issue was `spring stop` and it worked perfectly. chrs
